
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int pto = 22;
  public static final int bool = 6;
  public static final int doo = 15;
  public static final int distinto = 34;
  public static final int puublic = 18;
  public static final int mod = 40;
  public static final int ptoYcoma = 23;
  public static final int coma = 24;
  public static final int doublee = 9;
  public static final int prootected = 19;
  public static final int swiitch = 16;
  public static final int string = 7;
  public static final int iimport = 2;
  public static final int llavec = 26;
  public static final int llavea = 25;
  public static final int elsee = 12;
  public static final int claass = 3;
  public static final int menos = 37;
  public static final int mayorQ = 32;
  public static final int menor = 30;
  public static final int iff = 11;
  public static final int fiinal = 20;
  public static final int EOF = 0;
  public static final int parc = 28;
  public static final int mas = 36;
  public static final int chaar = 8;
  public static final int whilee = 14;
  public static final int para = 27;
  public static final int iguala = 35;
  public static final int error = 1;
  public static final int mayor = 29;
  public static final int or = 44;
  public static final int foor = 13;
  public static final int por = 38;
  public static final int ComentarioMultiLinea = 50;
  public static final int id = 47;
  public static final int incremento = 41;
  public static final int staatic = 21;
  public static final int object = 10;
  public static final int priivate = 17;
  public static final int voiid = 4;
  public static final int not = 45;
  public static final int and = 43;
  public static final int decremento = 42;
  public static final int iint = 5;
  public static final int menorQ = 33;
  public static final int div = 39;
  public static final int num = 46;
  public static final int asignacion = 31;
  public static final int decimal = 48;
  public static final int cadena = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "iimport",
  "claass",
  "voiid",
  "iint",
  "bool",
  "string",
  "chaar",
  "doublee",
  "object",
  "iff",
  "elsee",
  "foor",
  "whilee",
  "doo",
  "swiitch",
  "priivate",
  "puublic",
  "prootected",
  "fiinal",
  "staatic",
  "pto",
  "ptoYcoma",
  "coma",
  "llavea",
  "llavec",
  "para",
  "parc",
  "mayor",
  "menor",
  "asignacion",
  "mayorQ",
  "menorQ",
  "distinto",
  "iguala",
  "mas",
  "menos",
  "por",
  "div",
  "mod",
  "incremento",
  "decremento",
  "and",
  "or",
  "not",
  "num",
  "id",
  "decimal",
  "cadena",
  "ComentarioMultiLinea"
  };
}

